id: P007036
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25605
  title: ཡིག་གཟུགས་སྦྱོང་དེབ།
  author: ''
  volumes:
    6a41d3e693a340ebae649888f1ac56f9:
      image_group_id: I1KG25607
      title: ''
      volume_number: 1
      total_pages: 118
ebook_metadata:
  title: ཡིག་གཟུགས་སྦྱོང་དེབ།
  author: ''
  sku: P007036
  cover: cover.jpg
  layers:
  - pagination
