id: I2A9E7554
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T01:05:33+00:00'
last_modified: '2022-06-08T13:29:54.458501+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25605
  title: ཡིག་གཟུགས་སྦྱོང་དེབ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    '9458':
      image_group_id: I1KG25607
      title: Volume 1 of yig gzugs sbyong deb/
      total_pages: 118
      order: 1
      base_file: 9458.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
